compile:
	gcc -c ADT_linked_list.c
	gcc -c main.c
	gcc -o linked_list ADT_linked_list.o main.o

all:
	gcc -c ADT_linked_list.c
	gcc -c main.c
	gcc -o linked_list ADT_linked_list.o main.o
	./linked_list

help:
	@echo all - compile and execute
	@echo compile - compile and linking