compile:
	gcc -c ADT_queue.c
	gcc -c main.c
	gcc -o queue ADT_queue.o main.o

all:
	gcc -c ADT_queue.c
	gcc -c main.c
	gcc -o queue ADT_queue.o main.o
	./queue

help:
	@echo all - compile and execute
	@echo compile - compile and linking