compile:
	gcc -c ADT_linked_list.c main.c BST_Graph.c
	gcc -o graph ADT_linked_list.o main.o BST_Graph.o

all:
	gcc -o graph ADT_linked_list.c main.c BST_Graph.c
	./graph

help:
	@echo all - compile and execute
	@echo compile - compile and linking